INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (39, 'What kind of art is this?', '¿Qué tipo de arte es?', 'Quel mouvement est ce art?', 'Welche Art von Kunst ist das', 'T3');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (23, 'Which is the fastest way to travel there?', '¿Cuál es la manera más rapida para viajar?', 'Quelle route est le plus rapidement?', 'Was ist der schnellste weg, um dorthin zu gelangen', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (9, 'How do I get to a restaurant?', '¿Cómo voy a un restaurante?', 'Comment allez-vous au restaurant?', 'Wie bekomme ich in ein restaurant', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (21, 'What time does this open?', '¿A qué hora abre eso?', 'A quelle heure est-ce que on ouvre?', 'Wann ist es geoffnet', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (36, 'I am allergic to nuts', 'Soy alérgico a nueces', 'J''ai une allergie aux noix ', 'Ich bin allergisch gegen muttern', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (47, 'Someone Help Me!', '¡Ayúdame!', 'Aidez-moi!', 'Jemand mir helfen', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (10, 'How do I get to the hospital?', '¿Cómo voy al hospital?', 'Comment allez-vous a l''hopital?', 'Wie bekomme ich ins krankenhaus', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (11, 'Where is the bathroom?', '¿Dónde está el baño?', 'Où est la toilette?', 'Wo ist die Toilette', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (35, 'I am allergic to milk', 'Soy alérgico a leche.', 'J''ai une allergie au lait', 'Ich bin allergisch auf milch', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (12, 'Where is the ATM?', '¿Dónde está el ATM?', 'Où est le distributeur automatique?', 'Wo ist der geldautomat', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (32, 'May I have more...', '¿Me das más. . . por favór?', 'Je voudrais plus de..., s''il te plait', 'Ich kann mehr haben', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (14, 'Where is my room?', '¿Dónde está mi cuarto?', 'Où est ma chambre?', 'Wo ist mein Zimmer', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (24, 'Is this train going to ...?', '¿Está el trén que va a. . .', 'Où va le train?', 'Ist der zug Zu gehen', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (13, 'Where is the bus station?', '¿Dónde está la estación de autobús?', 'Où est la gare routiere?', 'Wo bifindet sich der Busbahnhof', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (50, 'What are some good places I should visit?', '¿Qué son lugares debo visitar?', 'Qu''est-ce que les bonnes sites touristiques et historiques?', 'Was sind einige gute Platze, die ich besuchen kann', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (25, 'Is this bus going to ...?', '¿Está el autobús que va a. . .', 'Où va le bus?', 'Ist der Bus zu gehen', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (18, 'Where can I buy an umbrella?', '¿Dónde puedo comprar un paraguas?', 'Où est-ce que vous achetez un parapluie?', 'Wo kann ich einen Regenschirm kaufen', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (15, 'Where is the train station?', '¿Dónde está la estación del trén?', 'Où est la gare?', 'Wo ist der Banhof', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (5, 'I would like some soda', 'Me gustaría refresco, por favór', 'Je veux du soda', 'Ich hatte gerne eine Cola', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (51, 'Good bye', '¡Adiós!', 'Au revoir', 'Auf wiedersehen', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (29, 'How can I get to the museum?', '¿Cómo voy al museo?', 'Comment allez-vous au musee?', 'Wie bekomme ich das Museum', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (41, 'My head hurts', 'Me duele la cabeza.', 'J''ai un mal de tete', 'Mein kopf tut weh', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (16, 'How much is this?', '¿Cuánto cuesta?', 'Combien coute?', 'Wie viel Kostat das', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (33, 'Please add sugar.', 'Añade azúcar por favór', 'Je voudrais plus du sucre, s''il te plait', 'Bitte fugen Sie zucker', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (49, 'Where can I find a tour guide?', '¿Dónde puedo encontrar un turisto?', 'Où est-ce que vous trouvez la guide touristique?', 'Wo finde ich einen Reisefuhrer', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (37, 'How do I log into the wifi?', '¿Cómo accedo al wifi?', 'Comment est-ce que vous entrez le wifi?', 'Wie logge ich mich in das wifi', 'T3');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (3, 'I would like a hamburger', 'Me gustaría comer un hamburguesa.', 'Je voudrais un hamburger?', 'Ich mochte einen Hamburger', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (46, 'My arm hurts', 'Me duele el brazo.', 'J''ai un mal de bras', 'Mein Arm tut weh', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (52, 'Thank you', 'Gracias', 'Merci', 'Danke', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (42, 'My stomach hurts', 'Me duele la estómago.', 'J''ai un mal de estomac', 'Mein Magen tut weh', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (19, 'Where can I buy sunscreen?', '¿Dónde puedo comprar protector solar?', 'Où est-ce que vous achetez de la creme solaire?', 'Wo kann ich sonnencreme kaufen', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (17, 'Where can I buy a map?', '¿Dónde puedo comprar una mapa?', 'Où est-ce que vous achetez une carte?', 'Wo kann ich eine Karte Kaufen', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (55, 'How are you?', '¿Cómo estás?', 'Comment allez-vous?', 'Wie geht es dir', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (34, 'I am allergic to gluten', 'Soy alérgico a gluten', 'J''ai une allergie au gluten', 'Ich bin allergisch gegen gluten', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (28, 'Where can I buy some souvenirs?', '¿Dónde puedo comprar recuerdos?', 'Où est-ce que vous achetez du souvenirs?', 'Wo kann ich einige souvenirs kaufen', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (43, 'My foot hurts', 'Me duele el pie.', 'J''ai un mal de pied', 'Mein FuB tut weh', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (44, 'My leg hurts', 'Me duele la pierna.', 'J''ai une mal de jambe', 'Mein Bein tut weh', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (20, 'When does this close?', '¿Cuándo cerrá?', 'A quelle heure est-ce que on ferme?', 'Wann wird dies in der Nahe', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (1, 'Hello', 'Hola', 'Bonjour', 'Gutentage', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (45, 'My throat hurts', 'Me duele la garganta.', 'J''ai une mal de gorge', 'Mein Hals tut weh', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (2, 'I would like ice cream', 'Me gustaría comer helado.', 'Je voudrais de la creme glacee', 'Ich mochte einige eis', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (22, 'Which restaurant do you recommend?', '¿Cuál restaurante me recomiendas?', 'Quel restaurant vous recommandez?', 'Welches restaurant empfehlen Sie', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (4, 'I would like some water', 'Me gustaría agua, por favór', 'Je veux de l''eau', 'Ich mochte etwas Wasser', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (26, 'Which hotel do you recommend?', '¿Cuál hotel me recomiendas?', 'Quel hotel vous recommandez?', 'Welches hotel empfehlen Sie', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (53, 'Your welcome', 'De nada.', 'De rein', 'Ihre begrussen', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (27, 'Which dish do you recommend?', '¿Cuál comida me recomiendas?', 'Quel plat vous recommandez?', 'Welches Gericht wurden Sie empfehlen', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (7, 'How do I get to the hotel?', '¿Cómo voy al hotel?', 'Comment allez-vous a l''hotel?', 'Anreise zum hotel', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (8, 'How do I get to the airport?', '¿Cómo voy al aeropuerto?', 'Comment allez-vous a l''aeroport?', 'Wie bekomme ich zum flughafen', 'T1');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (31, 'Where can I buy some groceries?', '¿Dónde puedo comprar comida?', 'Où est-ce que vous faites le courses?', 'Wo kann ich einige lebensmittel kaufen', 'T2');
INSERT INTO dictionary (id, en, es, fr, du, tier) VALUES (6, 'I would like some fruit', 'Me gustaría fruta, por favór', 'Je veux du fruits', 'Ich mochte etwas Obst', 'T1');